{"name": "Validate Accounts page object ", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.step('Browser Launched')\n    def LaunchBrowser():\n        try:\n            winName = getWindowName()\n>           Browser.switch_to.window(winName[1])\nE           TypeError: 'NoneType' object is not subscriptable\n\n..\\..\\Commonfunction.py:87: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"Validate Accounts page object \")\n    def test_LeftPanel ():\n        try:\n    \n>           LaunchBrowser()\n\nTC04_Accounts.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\na = (), kw = {}, __tracebackhide__ = True, params = OrderedDict(), args = []\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\n\nc:\\python36\\lib\\site-packages\\allure_commons\\_allure.py:157: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @allure.step('Browser Launched')\n    def LaunchBrowser():\n        try:\n            winName = getWindowName()\n            Browser.switch_to.window(winName[1])\n            Browser.close()\n            Browser.switch_to.window(winName[0])\n            Browser.get(\"https://tcdi-test.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=apps\")\n            sleep(5)\n            try:\n                fn_objExist(Browser.find_element_by_name(\"loginfmt\"))\n                Browser.find_element_by_id(\"i0116\").send_keys(\"test.fieldsales@cditechnologies.com\")\n                sleep(2)\n                WebDriverWait(Browser,140).until(EC.element_to_be_clickable((By.ID,\"idSIButton9\")))\n                Browser.find_element_by_id(\"idSIButton9\").click()\n                fn_rptStepDetails(\"Pass\", \"Login details entered & clicked on login button\")\n                WebDriverWait(Browser,140).until(EC.element_to_be_clickable((By.ID,\"i0118\")))\n                fn_objExist(Browser.find_element_by_id(\"i0118\"))\n                Browser.find_element_by_id(\"i0118\").send_keys(\"Tr0x@CRM\")\n                sleep(2)\n                fn_objExist(Browser.find_element_by_id(\"idSIButton9\"))\n                Browser.find_element_by_id(\"idSIButton9\").click()\n                fn_rptStepDetails(\"Pass\",\"Clicked on sign on button\")\n                fn_objExist(Browser.find_element_by_id(\"idBtn_Back\"))\n                Browser.find_element_by_id(\"idBtn_Back\").click()\n            except:\n                fn_rptStepDetails(\"Pass\", \"User Already loggedin !!!!\")\n            sleep(5)\n            fn_rptStepDetails(\"Pass\", \"Clicked on NO Button in the popup\")\n            WebDriverWait(Browser,140).until(EC.element_to_be_clickable((By.ID,\"AppLandingPage\")))\n            fn_objExist(Browser.find_element_by_id(\"AppLandingPage\"))\n            Browser.switch_to.frame(\"AppLandingPage\")\n            WebDriverWait(Browser,140).until(EC.element_to_be_clickable((By.XPATH,\"//*[@id='AppDetailsSec_1_Item_1']/div[1]\")))\n    \n    #         fn_objExist(Browser.find_element_by_xpath('//*[@id=\"AppDetailsSec_1_Item_1\"]/div[1]'))\n    #         Browser.find_element_by_xpath('//*[@id=\"AppDetailsSec_1_Item_1\"]/div[1]').click()\n            Browser.find_element_by_xpath(\"//div[contains(text(),'Field Sales')]\").click()\n            Browser.switch_to.window(winName[0])\n            sleep(20)\n            fn_rptStepDetails(\"Pass\", \"Logged into application!!!\")\n    \n            assert len(winName[0])>0\n        except Exception as e:\n            fn_CaptureScreenShot(\"Fail\", \"Failed in Launch browser function {}\".format(e))\n>           assert False\nE           AssertionError\n\n..\\..\\Commonfunction.py:127: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"Validate Accounts page object \")\n    def test_LeftPanel ():\n        try:\n    \n            LaunchBrowser()\n            fn_CaptureScreenShot(\"Pass\",\"After Browser Launch\")\n            fn_rptStepDetails(\"Pass\", \"Browser Launched Successfully\")\n            sleep(2)\n            fn_ClickHomeLink()\n            fn_ClickRecentLink()\n            fn_ClickDashboardsLink()\n            fn_ClickActivitiesLink()\n            fn_ClickAccountsLink()\n            fn_ClickContactsLink()\n            fn_ClickOpportunitiesLink()\n            fn_ClickQuotesLink()\n            fn_CaptureScreenShot(\"Pass\", \"Completed !!!\")\n            assert True\n    \n        except:\n            fn_CaptureScreenShot(\"Fail\", \"Unknown error look for error in report\")\n>           assert False\nE           assert False\n\nTC04_Accounts.py:34: AssertionError"}, "steps": [{"name": "Browser Launched", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\DELL\\eclipse-workspace\\CDI\\Commonfunction.py\", line 127, in LaunchBrowser\n    assert False\n"}, "steps": [{"name": "*******ScreenShot 'Failed in Launch browser function 'NoneType' object is not subscriptable' **********", "status": "passed", "attachments": [{"name": "Failed in Launch browser function 'NoneType' object is not subscriptable", "source": "8025bb9f-1081-4eed-a2f7-dee2508ef33b-attachment.PNG"}], "parameters": [{"name": "TestStatus", "value": "'Fail'"}, {"name": "TestStep", "value": "'Failed in Launch browser function 'NoneType' object is not subscriptable'"}], "start": 1604749264598, "stop": 1604749264627}], "start": 1604749264227, "stop": 1604749264627}, {"name": "*******ScreenShot 'Unknown error look for error in report' **********", "status": "passed", "attachments": [{"name": "Unknown error look for error in report", "source": "b332750b-e603-493f-b24d-e5a54a218b04-attachment.PNG"}], "parameters": [{"name": "TestStatus", "value": "'Fail'"}, {"name": "TestStep", "value": "'Unknown error look for error in report'"}], "start": 1604749264998, "stop": 1604749265044}], "attachments": [{"name": "stdout", "source": "2ed187f8-9862-4322-a293-f435a7149fc9-attachment.txt", "type": "text/plain"}], "start": 1604749264226, "stop": 1604749265045, "uuid": "96566d6b-51fd-4779-af08-6027611917c0", "historyId": "938ea0f0617aadc76e1f858f21aafa30", "testCaseId": "cd2ca439d427cd29863b796d22ffe827", "fullName": "scr.Accounts.TC04_Accounts#test_LeftPanel", "labels": [{"name": "parentSuite", "value": "scr.Accounts"}, {"name": "suite", "value": "TC04_Accounts"}, {"name": "host", "value": "GOOGLE"}, {"name": "thread", "value": "7044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scr.Accounts.TC04_Accounts"}]}